version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot_container
    command: node src/index.js
    restart: unless-stopped
    depends_on:
      - discord-auth-server
    volumes:
      - .:/usr/src/bot
      - /usr/src/bot/node_modules
    networks:
      - default

  discord-auth-server:
    build: .
    container_name: discord_auth_server
    command: node scripts/discord-auth-server.js
    restart: unless-stopped
    ports:
      - '${PORT_DISCORD_AUTH_SERVER}:${PORT_DISCORD_AUTH_SERVER}'
    networks:
      - default

networks:
  default:
